#!/bin/bash
# Powered by Apad.pro
# https://apad.pro/ednsplus
#
# Notes: EDNS-Plus for CentOS/RedHat 7+
#
sudo \cp -r /usr/local/ednsplus/systemd/*.service /etc/systemd/system && sudo systemctl daemon-reload && sudo systemctl start shadowsocks2 && sudo systemctl start dns2sockstw && sudo systemctl start dnsproxy && sudo systemctl start overture && sudo systemctl enable shadowsocks2 && sudo systemctl enable dns2sockstw && sudo systemctl enable dnsproxy && sudo systemctl enable overture && sudo systemctl status shadowsocks2 && sudo systemctl status dns2sockstw && sudo systemctl status dnsproxy && sudo systemctl status overture
